apiVersion: batch/v1
kind: CronJob
metadata:
  name: password-rotation
spec:
  schedule: "0 0 1 */3 *"  # Runs every 3 months
  jobTemplate:
    spec:
      template:
        spec:
          hostAliases:
          - ip: "3.120.3.139"
            hostnames:
            - vault
          containers:
          - name: password-rotation
            image: hazemataya/password-rotation
          restartPolicy: OnFailure