{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "hc-vault.fullname" . }}-{{ .Values.cronjob.name }}
  labels:
    {{- include "hc-vault.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.cronjob.name }}
            image: {{ .Values.cronjob.image }}
            imagePullPolicy: IfNotPresent
            {{- if or .Values.cronjob.command }}
            command: ["/bin/sh", "-c", {{ .Values.cronjob.command | quote}}]
            {{- end }}
            {{- if or .Values.cronjob.secretRef }}
            envFrom:
              - secretRef:
                  name: {{ .Values.cronjob.secretRef }}
            {{- end }}
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
            volumeMounts:
              - mountPath: /vault/audit
                name: audit-logs
          volumes:
            - name: audit-logs
              persistentVolumeClaim:
                claimName: vault-audit-log-pvc
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          nodeSelector:
            environment: vault
{{- end }}
