apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-audit-log-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
