cronjob:
  enabled: false
  image: xxxxxx.dkr.ecr.eu-central-1.amazonaws.com/vault:backup
  name: backup
  schedule: "30 23 * * *"
  restartPolicy: OnFailure
  secretRef: vault

mysql:
  enabled: true
  auth:
    rootPassword: root
    username: vault
    password: vault
    database: vault

vault:
  # Available parameters and their default values for the Vault chart are available using the following:
  # https://github.com/hashicorp/vault-helm/blob/main/values.yaml
  enabled: true

  injector:
    enabled: false

  server:
    enabled: true

    image:
      repository: "hashicorp/vault"
      tag: "1.9.3"
      pullPolicy: Always

    logLevel: "info"
    logFormat: "json"

    resources:
      requests:
        memory: 512Mi
        cpu: 400m
      limits:
        memory: 1Gi
        cpu: 600m

    affinity: |
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ template "vault.name" . }}-agent-injector
                  app.kubernetes.io/instance: "{{ .Release.Name }}"
                  component: webhook
              topologyKey: kubernetes.io/hostname

    ingress:
      enabled: true
      labels: {}
      annotations:
        kubernetes.io/ingress.class: nginx        
      activeService: false
      hosts:
        - host: vault
          paths: []
      
    readinessProbe:
      enabled: true

    livenessProbe:
      enabled: true

    service:
      enabled: true
      port: 8200
      targetPort: 8200
      
    dataStorage:
      enabled: false

    standalone:
      enabled: false

    ha:
      enabled: true
      replicas: 2
      raft:
        enabled: false
      
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "mysql" {
          address = "vault-mysql.default.svc.cluster.local"
          database = "vault"
          username = "vault"
          password = "vault"
          ha_enabled = "true"
        }
        
        service_registration "kubernetes" {}

  ui:
    enabled: true
    activeVaultPodOnly: true
    serviceType: "ClusterIP"
    externalPort: 8200
    targetPort: 8200
